- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - openstackclient-plugin-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - muranoclient-functional-test-mysql-backend
        - openstack-tox-cover:
            voting: false
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - muranoclient-functional-test-mysql-backend

    post:
      jobs:
        - openstack-tox-cover
- job:
    name: muranoclient-functional-test-mysql-backend
    parent: legacy-dsvm-base
    run: playbooks/legacy/muranoclient-functional-test-mysql-backend/run.yaml
    post-run: playbooks/legacy/muranoclient-functional-test-mysql-backend/post.yaml
    timeout: 4200
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
