- project:
    check:
      jobs:
        - openstack-tox-lower-constraints
        - muranoclient-functional-test-mysql-backend
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - muranoclient-functional-test-mysql-backend

- job:
    name: muranoclient-functional-test-mysql-backend
    parent: legacy-dsvm-base
    run: playbooks/legacy/muranoclient-functional-test-mysql-backend/run.yaml
    post-run: playbooks/legacy/muranoclient-functional-test-mysql-backend/post.yaml
    timeout: 4200
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
